### ISSUE TITLE
Modify branding (whitelabel)

### ISSUE THREAD

**Issue by zainfathoni** [zainfathoni/kawalmasjid#1]
- Brand colors with Tailwind CSS
- Initial content

Inspired by https://tabung.sg

**Comment by mhaidarhanif** [comment]
Most of the brand color implementation has been done.

Also updated with the new logo and open graph image, can check https://kawalmasj.id

![image](https://kawalmasj.id/assets/opengraph/kawalmasjid-og.png)

![image](https://user-images.githubusercontent.com/235584/233161698-4dd564d3-83ce-43a5-a3ca-20b6a1a5202c.png)

![image](https://user-images.githubusercontent.com/235584/233161747-8fdb3016-85eb-40fe-87b5-fc1b7c1559d8.png)

After all checked by @zainfathoni and @mazipan, then we can close this issue.

**Comment by mhaidarhanif** [comment]
Since there are a lot of things for the SEO and sitemap, let's separate them into a new issue. This one focus on the branding / white label.

@zainfathoni @mazipan Please check the branding implementation first.

**Comment by mhaidarhanif** [comment]
Looks good and fine for now. Let's consider this early rebrand as done.
