### ISSUE TITLE
Update all default logo ⏪ to 🕌

### ISSUE THREAD

**Issue by mazipan** [zainfathoni/kawalmasjid#13]
As described in the title

- [x] Text based in JSX
- [x] Favicon, PNG based

**Comment by mhaidarhanif** [comment]
I'll be updating this

In the internal chat we've decided about the logo/image

**Comment by mhaidarhanif** [comment]
Updated with the new logo, can check https://kawalmasj.id

![image](https://user-images.githubusercontent.com/235584/233161698-4dd564d3-83ce-43a5-a3ca-20b6a1a5202c.png)

![image](https://user-images.githubusercontent.com/235584/233161747-8fdb3016-85eb-40fe-87b5-fc1b7c1559d8.png)

After all checked from @zainfathoni and @mazipan, then we can close this issue.

**Comment by mhaidarhanif** [comment]
Looks good and fine for now. Let's consider this as done.
