### ISSUE TITLE
Collect and upload image assets for the Mosque images

### ISSUE THREAD

**Issue by mhaidarhanif** [zainfathoni/kawalmasjid#17]
# Chore

## Describe the chore

Need to decide where to store the assets to integrate with the image hosting 

## Additional context

Some options:

- Uploadcare
- ImageKit
- Cloudinary

**Comment by zainfathoni** [comment]
Let's use Uploadcare since it just launched its [file uploader](https://uploadcare.com/products/file-uploader/) recently which I believe would speed up our development effort.

**Comment by mhaidarhanif** [comment]
@zainfathoni just checked again for the new file uploader, it doesn't support React yet.

What's available for React is the previous/existing uploader package:

- https://uploadcare.com/docs/integrations/react
- https://www.npmjs.com/package/@uploadcare/react-widget

But it's still fine though.

**Comment by mhaidarhanif** [comment]
@zainfathoni Since it's so new, the docs might be confusing to navigate. But better than nothing.

The React example is here: https://github.com/uploadcare/blocks-examples/tree/main/examples/react-uploader

**Comment by mazipan** [comment]
Let's make this as a top priority issue.

This is an essential feature, since the main goal of the site is to provide the QR Code from the user.
