### ISSUE TITLE
Refine data modeling to store Place's fields, images, and verification system

### ISSUE THREAD

**Issue by zainfathoni** [zainfathoni/kawalmasjid#2]
- donations:
  - images: optional
  - urls: optional
- verification system

![Image](https://user-images.githubusercontent.com/6315466/232947012-f3df50d6-a966-41b0-93d7-79f6bf81db7b.png)

**Comment by mazipan** [comment]
To have better separation, how about split the description into several fields?
Such as: `addreess`, `contact`, `email`, `web`.

**Comment by mazipan** [comment]
Add grouping for the address, so it can be filtered later.

Let say: `province`, `district`, etc.

**Comment by zainfathoni** [comment]
> To have better separation, how about split the description into several fields? Such as: `address`, `contact`, `email`, `web`.

Sure, as long as we make them optional, that would be fine. WDYT, @mhaidarhanif?

**Comment by mhaidarhanif** [comment]
@mazipan @zainfathoni Yes that would be the plan.

The description field can be separated into:

- description
- address: Address model
- contact
- email
- websiteURL

Then the Address model can contain:

- province
- district
- etc

We were just in early stage and just started coding this morning 😀 So things are flexible to choose.

Here's a reference for inspiration on the Address model:

```
model Address {
  id String @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  name           String // Nama Alamat

  addressComplete      String? // The complete combined address name
  addressGoogleMapsURL String? // https://goo.gl/maps/1xABCDEF123456

  street        String? // Jl. Nama Jalan
  streetDetails String? // Optional details such as floor number
  subDistrict   String? // Kelurahan
  district      String? // Kecamatan
  city          String? // Kota/Kabupaten
  province      String? // Provinsi
  postalCode    String? // Kode pos
  countryCode   String? // Save as ID, not Indonesia

  countryId     String?
  provinceId    String?
  cityId        String?
  districtId    String?
  subDistrictId String?
  
  // Geolocation
  latitude      Decimal? // -90 to 90, Example: -6.1234567
  longitude     Decimal? // -180 to 180, Example: 106.1234567

  user   User?   @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId String?

  @@index([userId])
}
```

**Comment by mazipan** [comment]
This is just my two cents. Creating another model for Address is unnecessary for now since it's just one-to-one relationship.

There is no shareable Address.

It will hard to query/filter, since we need to do a nested select into the Address model. Let say when we want to filter the data based on province for example.

So make it flat will be better for a small use case.
