### ISSUE TITLE
Lailatul Qoding membangun Kawal Masjid

### ISSUE THREAD

**Issue by zainfathoni** [zainfathoni/kawalmasjid#23]
# Agenda

- [x] Perkenalan
- [x] Penjelasan Kawal Masjid mengapa, apa, & bagaimana
  - [x] Inspirasi dari tabung.sg
- [x] Walkthrough GitHub repository & issues
- [x] Tech stack discussion
  - [x] Remix web framework + React UI library
  - [x] Rewinds template
- [x] Pengembangan #17

**Comment by mhaidarhanif** [comment]
🙏 Done: https://zainf.dev/lailatul-qoding-1
