### ISSUE TITLE
Refine README and remove tech stack docs

### ISSUE THREAD

**Issue by mazipan** [zainfathoni/kawalmasjid#9]
We does not need to explain the whole tech stack, all the docs are live in the ⏪ Rewind readme instead.

We just need to include the simple Getting started for new contributor.

**Comment by mhaidarhanif** [comment]
I think @zainfathoni or you @mazipan will be better to handle this 😀 I leave it to you all

**Comment by zainfathoni** [comment]
> README has been updated to remove the tech stack. Next can inform how to contribute.

We can grab some inspirations (a.k.a. copy) the guidelines from here 😁

https://github.com/zainfathoni/pkode/blob/main/README.md

**Comment by mhaidarhanif** [comment]
This is considered done or not? Because the current README is much better now.

**Comment by zainfathoni** [comment]
I think so. What do you think, Mas @mazipan?
